# Generated by Django 4.1.5 on 2023-01-29 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0004_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='date',
            new_name='date2',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='user',
            new_name='user2',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='value',
            new_name='value2',
        ),
    ]
